version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true             # Enable Grafana metrics
      - GF_METRICS_BASIC_AUTH_USERNAME=metrics_user # Optional: Basic auth username for /metrics
      - GF_METRICS_BASIC_AUTH_PASSWORD=metrics_pass # Optional: Basic auth password for /metrics
    volumes:
      - ./grafana-resources/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-resources/dashboards:/etc/grafana/provisioning/dashboards

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf-config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
