{
 "title": "Grafana Internal Stats",
 "description": "Grafana Internal Metrics Dashboards",
 "tags": [
  "dashboards-as-code",
  "grafana",
  "internal metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(grafana_stat_total_orgs,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafana Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "grafana_build_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Count of Active users",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_active_admins{instance=\"$instance\"}",
     "legendFormat": "Active Admins"
    },
    {
     "expr": "grafana_stat_totals_active_editors{instance=\"$instance\"}",
     "legendFormat": "Active Editors"
    },
    {
     "expr": "grafana_stat_totals_active_viewers{instance=\"$instance\"}",
     "legendFormat": "Active Viewers"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Grafana Up",
   "type": "timeseries",
   "description": "Show if instance us Up or Down. Default Prometheus Metric.\n\nIf target is not reachable this will have 0 value",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "total amount of alerts",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_alerting_alerts{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Service Accounts",
   "type": "stat",
   "description": "Total Service Accounts",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_service_accounts{instance=\"$instance\"}",
     "legendFormat": "Service Accounts"
    },
    {
     "expr": "grafana_stat_total_service_account_tokens{instance=\"$instance\"}",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Admins",
   "type": "stat",
   "description": "Total amount of Admins",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_admins{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Organisations",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Folders",
   "type": "stat",
   "description": "total amount of folders",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Access Evaluations Total",
   "type": "stat",
   "description": "Access Evaluations Total in Timeframe",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(grafana_access_evaluation_count{instance=\"$instance\"}[$__interval])"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Alerts State",
   "type": "stat",
   "description": "State of the Alerts in orgs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_alerts{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alerts State",
   "type": "timeseries",
   "description": "State of the Alerts in orgs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "increase(grafana_alerting_alerts{instance=\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"10.96.0.209\",job=\"node-exporter\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"10.96.0.209\",job=\"node-exporter\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "DB Open Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_database_conn_open{instance=\"$instance\"} /\ngrafana_database_conn_max_open{instance=\"$instance\"} *100",
     "legendFormat": "open conn"
    }
   ]
  },
  {
   "title": "DB Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_database_conn_open{instance=\"$instance\"}",
     "legendFormat": "open conn"
    }
   ]
  },
  {
   "title": "Connection Wait Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(grafana_database_conn_wait_count_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "conn wait count"
    }
   ]
  },
  {
   "title": "Connection Wait Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(grafana_database_conn_wait_duration_seconds{instance=\"$instance\"}[$__interval])",
     "legendFormat": "conn wait count"
    }
   ]
  },
  {
   "title": "Responce Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "bargauge",
   "description": "http response status",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(grafana_api_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "increase(grafana_page_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "increase(grafana_proxy_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(grafana_api_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "increase(grafana_page_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "increase(grafana_proxy_response_status_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "timeseries",
   "description": "api login counters",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_login_post_total{instance=\"$instance\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{instance=\"$instance\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Get Duration Avg",
   "type": "timeseries",
   "description": "average dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{instance=\"$instance\"}[$__rate_interval]) / rate(grafana_api_dashboard_get_milliseconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "avg get duration"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "histogram",
   "description": "\nThe provided Prometheus query is designed to calculate the 50th | 90 | 99 percentile (median) of the latency distribution for Grafana alerting notifications over a specified time range. Here's a breakdown of the query and its description:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Save Duration Avg",
   "type": "timeseries",
   "description": "average dashboard save duration over  $__rate_interval minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{instance=\"$instance\"}[$__rate_interval]) / rate(grafana_api_dashboard_save_milliseconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "avg save duration"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "histogram",
   "description": "Dashboard Save Duration Quantiles",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{instance=\"$instance\",}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Search Duration Avg",
   "type": "timeseries",
   "description": "average dashboard search duration over $__rate_interval minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{instance=\"$instance\"}[$__rate_interval]) / \nrate(grafana_api_dashboard_search_milliseconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "histogram",
   "description": "Dashboard Search Duration Quantiles",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{instance=\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Dashboards Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true
  },
  {
   "title": "Dashboards Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "time_ms", "id": "1", "type": "avg" }
     ],
     "query": "\"https://grafana-lower.daeddo.com/d/*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Datasource Accessibility", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Datasources Accessibility",
   "type": "timeseries",
   "description": "Datasources Accessibility from Grafana",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=~\"thanos/thanos-query-.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "alias": "stg-influxdb.ph.esl-asia.com - $tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT count(\"uptime\") FROM \"system\" WHERE (\"host\"::tag =~ /^tpc-co-influx*/) AND $timeFilter GROUP BY time(10s), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "isc-co-graph01" }
     ]
    },
    {
     "alias": "gec-co-indb01.msgreen.dom - $tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_uptime",
     "query": "SELECT count(\"uptime\") FROM \"system\" WHERE (\"host\"::tag =~ /^tpc-co-influx*/) AND $timeFilter GROUP BY time(10s), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=", "value": "dsb-wallet" }
     ]
    },
    {
     "alias": "172.27.24.105 - $tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT count(\"uptime\") FROM \"system\" WHERE (\"host\"::tag =~ /^tpc-co-influx*/) AND $timeFilter GROUP BY time(10s), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "iss-k6-load01" }
     ]
    },
    {
     "alias": "10.104.36.33 - $tag_host",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_uptime",
     "query": "SELECT count(\"uptime\") FROM \"system\" WHERE (\"host\"::tag =~ /^tpc-co-influx*/) AND $timeFilter GROUP BY time(10s), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application::tag", "operator": "=", "value": "dsb-wallet" }
     ]
    },
    {
     "bucketAggs": [
      {
       "field": "l_host.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "l_host.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "host.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "host.hostname", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "hits",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hits", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Rule Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_uid.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"Clearing the state of the rule because it was updated\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "uname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "referer.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"/edit?returnTo=%2Falerting%2Flist\" AND method:\"POST\" AND path: \"/api/ruler/grafana/api/v1/rules/*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alerting Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "referer.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "time_ms", "id": "1", "type": "avg" }
     ],
     "query": "\"https://grafana-lower.daeddo.com/alerting/\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}