{
 "title": "General: Linux Host Monitoring",
 "tags": [
  "telegraf",
  "influxdb",
  "dashboards-as-code",
  "linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "env",
    "label": "Environment",
    "query": "SHOW TAG VALUES FROM system WITH KEY=env"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host WHERE env =~ /$env/"
   },
   {
    "name": "network_interface",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "interval",
    "label": "Sampling",
    "query": "10s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used_percent\") FROM \"swap\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Load Average (1m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1m",
     "query": "SELECT mean(load1) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "5m",
     "query": "SELECT mean(load5) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "15m",
     "query": "SELECT mean(load15) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "CPU - IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"offset\") - 493 FROM \"ntpq\" WHERE (\"host\" =~ /^$server$/  AND \"state_prefix\" = '*' ) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Process - Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total\") FROM \"processes\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Process - Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"zombies\") FROM \"processes\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Process - Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total_threads\") FROM \"processes\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_path",
     "query": "SELECT last(\"used_percent\") as used FROM \"disk\" WHERE (\"host\" =~ /^$server$/  AND \"path\" !~ /\\/var\\/lib\\/docker\\/.*/) AND $timeFilter GROUP BY \"path\"::tag , time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Endpoints Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_server",
     "query": "SELECT last(result_code) as result_code FROM \"http_response\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY server, method, time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Processes Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_pattern $tag_systemd_unit $tag_pidfile ",
     "query": "SELECT last(running) FROM \"procstat_lookup\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY pattern, pidfile, systemd_unit, time($interval) fill(null)"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "query": "SELECT mean(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" =~ /^$server$/ ) AND $timeFilter GROUP BY cpu, time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "1m",
     "query": "SELECT mean(load1) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    },
    {
     "alias": "5m",
     "query": "SELECT mean(load5) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    },
    {
     "alias": "15m",
     "query": "SELECT mean(load15) / mean(n_cpus) as load1_by_cpu FROM \"system\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered FROM \"mem\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"in\")) as \"in\", non_negative_derivative(mean(\"out\")) as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Contexts Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "switches",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval) fill(null) ORDER BY asc"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "switches",
     "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "alias": "switches",
     "query": "SELECT mean(entropy_avail) as entropy FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)"
    }
   ]
  },
  { "title": "Network Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval) ORDER BY asc"
    }
   ]
  },
  {
   "title": "TCP Handshake Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(tcp_activeopens), 1s) as activeopens,\n  non_negative_derivative(mean(tcp_attemptfails), 1s) as attemptfails,\n  non_negative_derivative(mean(tcp_estabresets), 1s) as estabresets,\n  non_negative_derivative(mean(tcp_passiveopens), 1s) as passiveopens,\n  non_negative_derivative(mean(tcp_retranssegs), 1s) as retranssegs,\n  non_negative_derivative(mean(tcp_outrsts), 1s) as outrsts,\n  non_negative_derivative(mean(tcp_inerrs), 1s) as inerrs\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "UDP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(udp_indatagrams), 1s) as indatagrams,\n  non_negative_derivative(mean(udp_outdatagrams), 1s) as outdatagrams\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(udp_incsumerrors), 1s) as udp_incsumerrors,\n  non_negative_derivative(mean(udp_inerrors), 1s) as udp_inerrors,\n  non_negative_derivative(mean(udp_noports), 1s) as udp_noports,\n  non_negative_derivative(mean(udp_rcvbuferrors), 1s) as udp_rcvbuferrors,\n  non_negative_derivative(mean(udp_sndbuferrors), 1s) as udp_sndbuferrors\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "ICMP Connections (Echo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(icmp_inechos), 1s) as inechos,\n  non_negative_derivative(mean(icmp_outechos), 1s) as outechos,\n  non_negative_derivative(mean(icmp_inechoreps), 1s) as inechoreps,\n  non_negative_derivative(mean(icmp_outechoreps), 1s) as outechoreps\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "ICMP Errors (Echo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(icmp_inerrors), 1s) as inerrors,\n  non_negative_derivative(mean(icmp_outerrors), 1s) as outerrors,\n  non_negative_derivative(mean(icmp_incsumerrors), 1s) as csumerrors\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Ipv4 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(ip_inreceives), 1s) as inreceives,\n  non_negative_derivative(mean(ip_outrequests), 1s) as outrequests\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Ipv4 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  non_negative_derivative(mean(ip_indiscards), 1s) as indiscards,\n  non_negative_derivative(mean(ip_outdiscards), 1s) as outdiscards,\n  non_negative_derivative(mean(ip_inhdrerrors), 1s) as inhdrerros,\n  non_negative_derivative(mean(ip_inaddrerrors), 1s) as inaddrerrors,\n  non_negative_derivative(mean(ip_inunknownprotos), 1s) as inunknownprotos,\n  non_negative_derivative(mean(ip_outnoroutes), 1s) as outnoroutes\nFROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Netfilter Conntrack Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(\"ip_conntrack_count\") as current, mean(\"ip_conntrack_max\") as max FROM \"conntrack\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  { "title": "Network Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Network Usage - $network_interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "query": "SELECT \n  non_negative_derivative(mean(bytes_recv),1s) as \"in\",\n  non_negative_derivative(mean(bytes_sent),1s) as \"out\"  \nFROM \"net\" WHERE host =~ /$server/ AND interface =~ /$network_interface/ AND $timeFilter GROUP BY time($interval), interface  fill(none)"
    }
   ]
  },
  {
   "title": "Network Errors - $network_interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "query": "SELECT \n  non_negative_derivative(mean(err_in),1s) as \"in\",\n  non_negative_derivative(mean(err_out),1s) as \"out\"  \nFROM \"net\" WHERE host =~ /$server/ AND interface =~ /$network_interface/ AND $timeFilter GROUP BY time($interval), interface  fill(none)"
    }
   ]
  },
  {
   "title": "Network Packets - $network_interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "query": "SELECT \n  non_negative_derivative(mean(packets_recv),1s) as \"in\",\n  non_negative_derivative(mean(packets_sent),1s) as \"out\"  \nFROM \"net\" WHERE host =~ /$server/ AND interface =~ /$network_interface/ AND $timeFilter GROUP BY time($interval), interface  fill(none)"
    }
   ]
  },
  {
   "title": "Network Packets Drops - $network_interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$tag_interface: $col",
     "query": "SELECT \n  non_negative_derivative(mean(drop_in)) as \"in\",\n  non_negative_derivative(mean(drop_out)) as \"out\"  \nFROM \"net\" WHERE host =~ /$server/ AND interface =~ /$network_interface/ AND $timeFilter GROUP BY time($interval), interface fill(none)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Disk I/O Requests - $disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_name: $col",
     "query": "SELECT \n  non_negative_derivative(mean(reads),1s) as \"read\",\n  non_negative_derivative(mean(writes),1s) as \"write\" \nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), \"name\""
    }
   ]
  },
  {
   "title": "Disk I/O Bytes - $disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name: $col",
     "query": "SELECT \n  non_negative_derivative(mean(read_bytes),1s) as \"read\",\n  non_negative_derivative(mean(write_bytes),1s) as \"write\" \nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), \"name\""
    }
   ]
  },
  {
   "title": "Disk I/O Time - $disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name: $col",
     "query": "SELECT \n  non_negative_derivative(mean(read_time),1s) as \"read\",\n  non_negative_derivative(mean(write_time),1s) as \"write\" \nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), \"name\""
    }
   ]
  },
  {
   "title": "Disk I/O Requests Queued Time - $disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "query": "SELECT \n  non_negative_derivative(mean(io_time),1s) as \"queued\"\nFROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), \"name\""
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_device: $tag_path",
     "query": "SELECT mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" !~ /\\/var\\/lib\\/docker\\/.*/ AND $timeFilter GROUP BY time($interval), \"host\", \"device\", \"path\""
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_path",
     "query": "SELECT last(\"used_percent\") as used FROM \"disk\" WHERE (\"host\" =~ /^$server$/  AND \"path\" !~ /\\/var\\/lib\\/docker\\/.*/) AND $timeFilter GROUP BY \"path\"::tag , time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Inodes Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_device: $tag_path",
     "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" !~ /\\/var\\/lib\\/docker\\/.*/ AND $timeFilter GROUP BY time($interval), \"host\", \"device\", \"path\""
    }
   ]
  },
  {
   "title": "Disk Inodes Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_path",
     "query": "SELECT mean(\"inodes_free\") as free FROM \"disk\" WHERE (\"host\" =~ /^$server$/  AND \"path\" !~ /\\/var\\/lib\\/docker\\/.*/) AND $timeFilter GROUP BY \"path\"::tag , time($interval) fill(null)"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Process Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT \n  last(blocked) as blocked,\n  last(running) as running,\n  last(stopped) as stopped,\n  last(zombies) as zombies,\n  last(dead) as dead,\n  last(sleeping) as sleeping,\n  last(unknown) as unknown\nFROM \"processes\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Processes Status History",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_pattern$tag_pidfile$tag_systemd_unit",
     "query": "SELECT \n  mean(running)\nFROM \"procstat_lookup\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY pattern, pidfile, systemd_unit, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_process_name",
     "query": "SELECT \n  mean(cpu_usage)\nFROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name, pattern, pidfile, systemd_unit, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_process_name",
     "query": "SELECT \n  mean(memory_usage)\nFROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name, pattern, pidfile, systemd_unit, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Process File Descriptors (FD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_process_name",
     "query": "SELECT \n  mean(num_fds)\nFROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name, pattern, pidfile, systemd_unit, time($interval) fill(none)"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Endpoints Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "query": "SELECT count(result_code) FROM (\n  SELECT last(result_code)  as result_code FROM \"http_response\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY server, method, result, time($interval) fill(null)\n) WHERE $timeFilter GROUP BY result, time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Endpoints Status History",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_method",
     "query": "SELECT last(result_code) as result_code FROM \"http_response\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY server, method, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Endpoints Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_method",
     "query": "SELECT mean(response_time) as result_code FROM \"http_response\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY server, method, time($interval) fill(none)"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Docker Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_containers\") as running, \"server_version\" as version FROM \"docker\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Number of Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$co",
     "query": "SELECT last(\"n_containers\") as containers FROM \"docker\"  WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Number of Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$co",
     "query": "SELECT last(\"n_images\") as images FROM \"docker\"  WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Container Status History",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "query": "SELECT difference(last(uptime_ns)) FROM \"docker_container_status\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY container_name, time($interval) fill(0)"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$co",
     "query": "SELECT last(\"n_containers_running\") as running FROM \"docker\"  WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$co",
     "query": "SELECT last(\"n_containers_stopped\") as stopped FROM \"docker\"  WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Paused Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$co",
     "query": "SELECT last(\"n_containers_paused\") as paused FROM \"docker\"  WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Docker Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "query": "SELECT mean(usage_percent) FROM \"docker_container_cpu\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY container_name, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Docker Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "query": "SELECT mean(usage_percent) FROM \"docker_container_mem\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY container_name, time($interval) fill(none)"
    }
   ]
  },
  {
   "title": "Docker Container Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_container_name: $col",
     "query": "SELECT \n  non_negative_derivative(mean(rx_bytes),1s) as \"in\",\n  non_negative_derivative(mean(tx_bytes),1s) as \"out\"  \nFROM \"docker_container_net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY container_name, network, time($interval)  fill(none)"
    }
   ]
  }
 ]
}