---

- name: Check if monitoring stack is running
  ansible.builtin.command:
    cmd: docker compose -f {{ ms_compose_config_path }} ps -qa
  register: stack_status
  changed_when: false
  failed_when: false

- name: Set fact for stack status
  ansible.builtin.set_fact:
    stack_configured: "{{ stack_status.stdout_lines | length > 0 }}"

- name: Import install_packages.yml
  ansible.builtin.import_tasks:
    file: install_packages.yml
  when: ms_docker_install_packages | default(false) | bool

- name: Import assertions.yml
  ansible.builtin.import_tasks:
    file: assertions.yml

- name: Import configure.yml
  ansible.builtin.import_tasks:
    file: configure.yml

- name: Import restart_stack.yml
  ansible.builtin.import_tasks:
    file: restart_stack.yml
  when: stack_configured and restart_stack | default(false) | bool

- name: Import stop_stack.yml
  ansible.builtin.import_tasks:
    file: stop_stack.yml
  when: stack_configured and stop_stack | default(false) | bool
