---
- name: Wait for 1 minute
  ansible.builtin.wait_for:
    timeout: 60

- name: Check status of Docker Compose services
  ansible.builtin.command:
    cmd: docker compose -f {{ ms_compose_config_path }} ps --format json
  register: docker_compose_status
  changed_when: false

- name: Parse Docker Compose status
  ansible.builtin.set_fact:
    service_statuses: "{{ docker_compose_status.stdout_lines | map('from_json') | list }}"

- name: Set fact for stack status
  ansible.builtin.set_fact:
    all_services_running: >-
      {{
        service_statuses | length > 0 and
        (service_statuses | selectattr('State', 'eq', 'running') | list |
        length == service_statuses | length)
      }}

- name: Verify services status
  ansible.builtin.assert:
    that:
      - all_services_running
    fail_msg: >-
      Not all services are running. Current statuses: {{
        service_statuses | map(attribute='Name') | zip(service_statuses | map(attribute='State')) | list
      }}
    success_msg: "All services are running"
