---
- name: Deploy Monitoring Stack
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Install Docker Compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Copy files to VM
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/opt/monitoring-stack/"
        remote_src: no
      loop:
        - docker-compose.yml
        - grafana-resources/

    - name: Start Monitoring Stack
      ansible.builtin.shell: |
        cd /opt/monitoring-stack
        docker-compose up -d
